"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
def fib_till(n):
    fib_till = [1,2]
    
    for i in range(2, n+1):
        fib_till.append(fib_till[-1] + fib_till[-2])
    
    return fib_till

sum_even_fib = 0
for i in fib_till(32):
    if i%2==0:
        sum_even_fib += i
print(sum_even_fib)        
